apiVersion: v1
kind: Namespace
metadata:
  name: quiz-4
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: practice-cluster-admin-rolebinding-anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: system:anonymous
---
apiVersion: v1
kind: Pod
metadata:
  name: quiz-4
  namespace: quiz-4
  labels:
    app: quiz-4
spec:
  containers:
  - name: target-pod
    image: aeifkz/my-ubuntu:v1.0
    ports:
      - containerPort: 30089
    securityContext:
      capabilities:
        drop:
          - all
---
apiVersion: v1
kind: Service
metadata:
  name: service-quiz4
  namespace: quiz-4
spec:
  type: NodePort
  ports:
  - port: 8084
    nodePort: 30394
    protocol: TCP
    targetPort: 30089
  selector:
    app: quiz-4
