apiVersion: v1
kind: Namespace
metadata:
  name: quiz-5
---
apiVersion: v1
kind: Pod
metadata:
  name: quiz-5
  namespace: quiz-5
  labels:
    app: quiz-5
spec:
  containers:
  - name: target-pod
    image: aeifkz/my-ubuntu:v1.0
    ports:
      - containerPort: 30089
    securityContext:
      privileged: false

---
apiVersion: v1
kind: Pod
metadata:
  name: quiz-5-server
  namespace: quiz-5
  labels:
    app: quiz-5-server
spec:
  containers:
  - name: server-pod
    image: aeifkz/my-ubuntu:v1.0
    ports:
      - containerPort: 8000
    command:
      - "python3"
      - "-m"
      - "http.server"
      - "8000"
---
apiVersion: v1
kind: Pod
metadata:
  name: quiz-5-client
  namespace: quiz-5
  labels:
    app: quiz-5-client
spec:
  containers:
  - name: client-pod
    image: aeifkz/my-ubuntu:v1.0
    command:
      - "/tools/client.sh"
      - "service-quiz5-server"
      - "8000"
      - "The_Quintessential_Quintuplets"
---
apiVersion: v1
kind: Service
metadata:
  name: service-quiz5
  namespace: quiz-5
spec:
  type: NodePort
  ports:
  - port: 8085
    nodePort: 30395
    protocol: TCP
    targetPort: 30089
  selector:
    app: quiz-5
---
apiVersion: v1
kind: Service
metadata:
  name: service-quiz5-server
  namespace: quiz-5
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: quiz-5-server
