apiVersion: v1
kind: Namespace
metadata:
  name: quiz-1
---
apiVersion: v1
kind: Pod
metadata:
  name: quiz-1
  namespace: quiz-1
  labels:
    app: quiz-1
spec:
  containers:
  - name: target-pod
    image: aeifkz/my-ubuntu:v1.0
    ports:
      - containerPort: 30089
    securityContext:
      capabilities:
        drop:
          - all
        add:
          - SYS_MODULE
---
apiVersion: v1
kind: Service
metadata:
  name: service-quiz1
  namespace: quiz-1
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30390
    protocol: TCP
    targetPort: 30089
  selector:
    app: quiz-1

